name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.11
        with:
          heroku_api_key: ${{secrets.6964190d-f4c4-41da-9e08-1b7c0ea849c6}}
          heroku_app_name: "thawing-garden-21789"
          heroku_email: "lilylynettethomas@gmail.com"